### ISSUE TITLE
need to add image for variants?

### ISSUE THREAD

**Issue by railsfactory-ferdinand** [jsqu99/spree_flexi_variants#38]
hi i just want to add a specific image for every option type value .since we don't have any variants for spree_flexi_variant how it would be done? and how to check whether the particular variant available in stock already.is that possible?Thanks for you help ...

**Comment by wandtasie** [comment]
The problem is: you can have multiple ad hoc options for one product. If you add an image to each ad hoc option value, you can't know which should appear on products page. 
If you just got one option that changes the images, you could use normal variants for this and use the ad hoc options for other options of the product, For example, selling t-shirts you could use ad hoc option values for the size cause this wouldn't change the image and normal variants for the color, cause this would change the image...

**Comment by railsfactory-ferdinand** [comment]
Thankyou for your kind response
